a, b = eval(input())
print(a, b, type(a), type(b))
print("2:", a > b)
print("3:", not a > b)
print("4:", a > b or a == b)
print("5:", a >= b)
print("6:", 3 < b <= 7)
print("7:", b > 3 and 7 >= b)
print("8:", a % 2 == 1)
print("9:", a % 2 == 1 and b % 2 == 0)
print("10:", max(a, b) % min(a, b) == 0)
print("11:", a != b)
