# 画五星红旗
import turtle as t

t.setup(600, 400, 0, 0)
t.bgcolor("red")
t.fillcolor("yellow")
t.color('yellow')
t.speed(5)
t.begin_fill()
t.up()
t.goto(-280, 100)
t.down()
for i in range(5):
    t.forward(150)
    t.right(144)
t.end_fill()
t.begin_fill()
t.up()
t.goto(-100, 180)
t.setheading(305)
t.down()
for i in range(5):
    t.forward(50)
    t.left(144)
t.end_fill()
t.begin_fill()
t.up()
t.goto(-50, 110)
t.setheading(30)
t.down()
for i in range(5):
    t.forward(50)
    t.right(144)
t.end_fill()
t.begin_fill()
t.up()
t.goto(-40, 50)
t.setheading(5)
t.down()
for i in range(5):
    t.forward(50)
    t.right(144)
t.end_fill()
t.begin_fill()
t.up()
t.goto(-100, 10)
t.setheading(300)
t.down()
for i in range(5):
    t.forward(50)
    t.left(144)
t.end_fill()
t.hideturtle()
t.done()
